name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name:  ${{secrets.HEROKU_APP_NAME_STAGING}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
        env:
          SQLALCHEMY_DATABASE_URL: ${{secrets.SQLALCHEMY_DATABASE_URL_STAGING }}
          GOOGLE_API_ADDRESS_KEY: ${{ secrets.GOOGLE_API_ADDRESS_KEY }}
